### ISSUE TITLE
CI Runner's cleanup steps before `sdw-admin --apply` use code from new commit

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-workstation-ci#38] opened 2023-09-26 22:01 UTC
Hi folks, not super familiar with the work in this repo so hopefully this ticket makes sense - apologies if not.

I was reviewing the [logs from a recent WIP CI run](https://ws-ci-runner.securedrop.org/2023-09-26-143647784509.log.txt) (wip PR [here](https://github.com/freedomofpress/securedrop-workstation/pull/917)) and I noticed that very early in the logs, the cleanup logic runs (`sudo qubesctl state.sls sd-clean-default-dispvm` and `sudo qubesctl state.sls sd-clean-all`).  First of all I was a little surprised that the cleanup logic runs before the `apply` run, but secondly the cleanup logic that runs is the updated cleanup logic (from the commit caught by the webhook), but the provisioning steps from that same commit haven't run yet, so the cleanup logic will fail.

(To make that into a less confusing sentence: the PR I linked changes the base fedora template to fedora-38, so it includes references in provisioning and removal for f38 templates. If the cleanup logic is run first, the ci runner looks for fedora 38 templates to remove, which are not yet present).

So my first question: Am I understanding what's happening correctly? And if so, my second question: unfortunately, cleanup-then-provision is not currently a well-supported state. Is that the only way to run the workstation CI test runner (i.e is there a 'fresh install' possibility that can spin up a system never provisioned with SDW)?
 
Thank you!

**Comment by mig5** [comment] 2023-09-26 23:13
Hi @rocodes,

> Am I understanding what's happening correctly?

Yes, with a small nuance: there is indeed a 'cleanup logic' that *can* occur at the start of the process, and is what you are seeing here. However, that *only* happens if the previous build failed (in the CI script, we call this being left in a 'dirty' state).

If the previous build was a success, the standard cleanup occurs at the end, and the system is considered 'clean' after that - so there is no need for the next build to perform any optimistic early cleanup.

There were several reasons we did this. The main ones were:

1) There were corner cases (one such case was a bug in the CI script itself) which could cause an early exception of the script leaving the system in a sort of 'half provisioned' state - the final cleanup never got a chance to run (https://github.com/freedomofpress/securedrop-workstation-ci/issues/13)

2) At some point, someone in the SD team (I think it might've been you, actually?) asked for the build to *immediately* exit if one of the steps failed, rather than continue on beyond the 'failure' step - so as to save time waiting for the results from CI, since it's a long process. (Forcing it to keep running and not abort on the first 'failure' was the original design, intended exactly to avoid the problem you're describing).

In short: in order to support a complete 'short circuit, abort everything', we *need* to somehow handle cleanup outside of that CI run, so marking a 'dirty' state on disk, and evaluating that at the start of the next run, is the simplest solution.

So this sounds like another interesting corner case, where the cleanup logic itself is the problem.


> unfortunately, cleanup-then-provision is not currently a well-supported state. Is that the only way to run the workstation CI test runner (i.e is there a 'fresh install' possibility that can spin up a system never provisioned with SDW)?

Right now, yes, I'm afraid. The CI is literally running on a physical X1 carbon with a long-running Qubes installation - it's not an IaaS sort of provision system on bare metal.

I am experimenting with one of three possible fixes to get you out of the immediate woods: I'm trying to re-run an older CI run on a different commit, in an effort to complete a 'standard' cleanup with the original cleanup logic.

If that doesn't work, I think I'll have to prepare some manual steps for someone with physical access to the X1 to perform a manual cleanup and clear the 'dirty' state.

If that can't be done in a reasonable amount of time, I'll resort to switching us over to the backup X1, which I know can be reached by someone physically.

As to the longer term fix, I'm not sure what to do. The issue of 'cleanup logic on that commit is the problem' is interesting. Would it make sense for us to somehow switch to a different commit's copy of the sdw-admin.py for the 'early cleanup' logic? I can see that working maybe in this case, but maybe not in others,  e.g where an older copy of sdw-admin.py might not properly clean up everything that a newer commit created.

**Comment by mig5** [comment] 2023-09-26 23:20
BTW @rocodes , it looks like the two latest builds succeeded at the 'early cleanup' step

https://ws-ci-runner.securedrop.org/2023-09-26-181239651957.log.txt
https://ws-ci-runner.securedrop.org/2023-09-26-181955579640.log.txt

They are now failing at the standard `make dev` step in what is effectively a 'fresh' setup again.

**Comment by rocodes** [comment] 2023-09-26 23:23
Hey @mig5, thank you for the awesome and very detailed summary. This makes sense; I think the last I heard of the sd ci runner it was in the context of an attempted GCE setup or similar, not a physical device. (And part of wanting to cut out early was to avoid burning server CI minutes, which maybe isn't applicable in this case).

I need a little more time to digest the rest of your comments, but yes, in this case the cleanup logic being the 'old' cleanup logic would have made sense-- but I don't think that you should necessarily rush to change anything at this stage. I think we should do a little more diligence on our side and then assess the CI situation and what behaviour we might request before we get you to get your hands dirty.

(tbh part of pushing a draft PR was to check out what exactly CI is doing. I've also got it building locally - the early teardown wasn't the only problem with this PR and I think it's just throwing up an error, not stopping the build. It's just an oddity and the kind of thing that might bite us later on, since the setup/teardown is hard to reason about)

**Comment by mig5** [comment] 2023-09-26 23:28
No worries! Yes, we gave up on the GCE solution, as it was too hard to achieve. (We also looked at experimenting with LVM snapshots to return to a 'fresh' state even on regular hardware - too hard :( 

To better understand the current setup, see the diagram in the README of this repo. In the diagram, 'sd-ssh' is a Qube on the dom0, and that's the X1. The Github webhook can reach that system via Tailscale.

Indeed, it looks like the early teardown/cleanup is not actually the root cause of the error here, just a surprise. But it's all valid points: the fact that we rely on SDW CI's own scripts to handle the teardown really *is* a double-edged sword: 

 * on the one hand, it's such a great way to test the script itself works, and it also means we don't have to be playing 'catch up' in the CI logic, to ensure that the cleanup steps we do match the standard cleanup steps in your script as closely as possible.
 * on the other hand, if one day the sdw-admin cleanup logic becomes a problem (and I think it has happened before), it can get us into an awkward state.

**Comment by rocodes** [comment] 2023-09-26 23:35
Thanks for your time on this. I think using the "last known good" setup/teardown logic (eg the logic from the tip of `main` as opposed to the PR) before the new RPM is installed and applied would be better than using the PR logic, as we do now, but will chat with the team about our overall CI goals before we start seriously proposing any changes. (And we may have another wrinkle as we figure out how to test on 4.2 rc3s as well as 4.1 stable).

**Comment by mig5** [comment] 2024-01-02 22:10
To summarise the above:

1) The current implementation of SDW CI does not do a complete 'reset' of the system after running the CI, but relies on the SDW `sdw-admin.py` script's own 'destroy' logic. This is a double-edged sword: it gives us an 'eating our own dogfood' automated test of that destroy logic, but if there *are* bugs in that logic, it can cause problems for the CI.

2) If a build fails, the environment is considered 'dirty' and the teardown occurs at the start of the *next* build. This is done so that if something fails, it aborts the build immediately (saving time on the CI build process itself). There is also the opportunity to debug on the CI machine in its broken state if it doesn't delete everything right away.

It is generally agreed that a more robust 'reset' method is desirable rather than relying on the sdw-admin.py script in SDW itself. Typically this would involve a totally rebuilt Qubes environment every time. To do this, we will need to rearchitect the entire SDW CI system to use a bare-metal provider and totally new scripts/terraform to build a Qubes environment each time as part of CI.

Since we are tracking that already elsewhere (https://github.com/freedomofpress/securedrop-engineering/issues/83) I will close this out.

**Closed by mig5** 2024-01-02 22:10 UTC
